### ISSUE TITLE
Field containing repetition of 3 components is losing one of the components on first repetition.

### ISSUE THREAD

**Issue by Andycharalambous** [pjlammertyn/HL7toXDocumentParser#1]
In the following HL7 segment:

`ZIT|1|2|3|CA^2.0000^257.6600~EA^1.0000^128.8300|1094`

ZIT.4 contains 2 repetitions of 3 components. When I parse this with HL7toXDocumentParser, I get:

```
<ZIT.4>
<ZIT.4.1>CA</ZIT.4.1>
<ZIT.4.2>2.0000</ZIT.4.2>
<ZIT.4.3>EA</ZIT.4.3>
<ZIT.4.4>1.0000</ZIT.4.4>
<ZIT.4.5>128.8300</ZIT.4.5>
</ZIT.4>
```

Note the lack of 257.6600 component. There should be 6 components, not 5. Is this a problem with my HL7 or the parser?

Thanks

**Comment by pjlammertyn** [comment]
Your correct, there is a problem with with the field repetition implementation.
I will change it so the XML output will be like this:

```
    <ZIT.4>
      <ZIT.4.1>CA</ZIT.4.1>
      <ZIT.4.2>2.0000</ZIT.4.2>
      <ZIT.4.3>257.6600</ZIT.4.1>
    </ZIT.4>
    <ZIT.4>
      <ZIT.4.1>EA</ZIT.4.1>
      <ZIT.4.2>1.0000</ZIT.4.2>
      <ZIT.4.3>128.8300</ZIT.4.3>
    </ZIT.4>
```

see commit: c9d8f7e264f2fbfa5792d210718dc03f0bbeb97b and 3a65fe43a32dc5407aa12977ddd829fd00894ad7
